builds:
  - id: dumbsync-index
    main: ./cmd/index/main.go
    binary: dumbsync-index
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: dumbsync
    main: ./cmd/sync/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
